controller_list:
  - name: fake_arm_left_controller
    type: $(arg execution_type)
    joints:
      - gripper_arm_bl_rotate
      - gripper_bl_rotate
      - gripper_ball_bl_rotate
  - name: fake_arm_right_controller
    type: $(arg execution_type)
    joints:
      - gripper_arm_fr_rotate
      - gripper_fr_rotate
      - gripper_ball_fr_rotate
  - name: fake_arrow_controller
    type: $(arg execution_type)
    joints:
      - throwing_slide
      - throwing_rotate
      - arrow_holder_slide
initial:  # Define initial robot poses.
  - group: arm_left
    pose: default_left
  - group: arm_right
    pose: default_right
  - group: arrow
    pose: arrow_default