throwing_bot_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  roller_rotate_fr_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: roller_rotate_fr_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  roller_rotate_fr_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: roller_rotate_fr_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  roller_rotate_bl_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: roller_rotate_bl_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  roller_rotate_bl_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: roller_rotate_bl_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_arm_fr_rotate_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_arm_fr_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_arm_bl_rotate_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_arm_bl_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_fr_rotate_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_fr_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_ball_fr_rotate_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_ball_fr_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_bl_rotate_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_bl_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_ball_bl_rotate_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_ball_bl_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arrow_holder_slide_position_controller:
    type: effort_controllers/JointPositionController
    joint: arrow_holder_slide
    pid: {p: 100.0, i: 0.01, d: 10.0}
  throwing_slide_position_controller:
    type: effort_controllers/JointPositionController
    joint: throwing_slide
    pid: {p: 100.0, i: 0.01, d: 10.0}
  throwing_rotate_position_controller:
    type: effort_controllers/JointPositionController
    joint: throwing_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arrow_grasper_fr_1_rotate_position_controller:
    type: effort_controllers/JointPositionController
    joint: arrow_grasper_fr_1_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arrow_grasper_fr_2_rotate_position_controller:
    type: effort_controllers/JointPositionController
    joint: arrow_grasper_fr_2_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arrow_grasper_bl_1_rotate_position_controller:
    type: effort_controllers/JointPositionController
    joint: arrow_grasper_bl_1_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arrow_grasper_bl_2_rotate_position_controller:
    type: effort_controllers/JointPositionController
    joint: arrow_grasper_bl_2_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}
