local_costmap:
  global_frame: odom
  robot_base_frame: dummy
  update_frequency: 5 
  publish_frequency: 2
  static_map: true
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.025
  transform_tolerance: 0.5
  cost_scaling_factor: 3
  inflation_radius: 0.1
