controller_list:
  - name: fake_arm1_controller
    joints:
      - gripper_arm_bl_rotate
  - name: fake_hand1_controller
    joints:
      - gripper_bl_rotate
      - gripper_ball_bl_rotate
  - name: fake_arm2_controller
    joints:
      - gripper_arm_fr_rotate
  - name: fake_hand2_controller
    joints:
      - gripper_fr_rotate
      - gripper_ball_fr_rotate
  - name: fake_arrow_holder_controller
    joints:
      - arrow_holder_slide
  - name: fake_rotating_chamber1_controller
    joints:
      - roller_rotate_bl_1
      - roller_rotate_bl_2
  - name: fake_rotating_chamber2_controller
    joints:
      - roller_rotate_fr_1
      - roller_rotate_fr_2
initial:  # Define initial robot poses.
  - group: arm1
    pose: init_arm1
  - group: hand1
    pose: pick_hand1
  - group: arm2
    pose: init_arm2
  - group: hand2
    pose: init_hand2
  - group: rotating_chamber1
    pose: init_rotation1