# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_left
  joint_model_group_pose: default_left
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - gripper_arm_bl_rotate
    - gripper_bl_rotate
    - gripper_ball_bl_rotate
    - gripper_arm_fr_rotate
    - gripper_fr_rotate
    - gripper_ball_fr_rotate
    - roller_rotate_bl_1
    - roller_rotate_bl_2
    - roller_rotate_fr_1
    - roller_rotate_fr_2
    - throwing_slide
    - throwing_rotate
    - arrow_grasper_bl_1_rotate
    - arrow_grasper_bl_2_rotate
    - arrow_grasper_fr_1_rotate
    - arrow_grasper_fr_2_rotate
    - arrow_holder_slide
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []