simple_model:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
 
  wheel_front_left_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_1
    pid: {p: 1.0, i: 0.0, d: 1.0}

  wheel_front_right_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_2
    pid: {p: 1.0, i: 0.0, d: 1.0}

  wheel_rear_left_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_3
    pid: {p: 1.0, i: 0.0, d: 1.0}

  wheel_rear_right_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_4
    pid: {p: 1.0, i: 0.0, d: 1.0}

  gazebo_ros_control:
    pid_gains:
      wheel_1 : {p: 1.0, i: 0.0, d: 1.0}
      wheel_2 : {p: 1.0, i: 0.0, d: 1.0}
      wheel_3 : {p: 1.0, i: 0.0, d: 1.0}
      wheel_4 : {p: 1.0, i: 0.0, d: 1.0}