controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      []
  - name: fake_turn_table_controller
    type: $(arg execution_type)
    joints:
      - turn_table_rotation
initial:  # Define initial robot poses.
  - group: turn_table
    pose: default_table