defense_bot_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  gripper_ball_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_ball_rotation
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rack_slider_position_controller:
    type: effort_controllers/JointPositionController
    joint: rack_slider
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lead_screw_slider_position_controller:
    type: effort_controllers/JointPositionController
    joint: lead_screw_slider
    pid: {p: 100.0, i: 0.01, d: 10.0}
  end_effector_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: end_effector_rotation
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_rotation
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_arm_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_arm_rotation
    pid: {p: 100.0, i: 0.01, d: 10.0}
  turn_table_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: turn_table_rotation
    pid: {p: 100.0, i: 0.01, d: 10.0}
