global_costmap:
  global_frame: map
  robot_base_frame: dummy
  update_frequency: 5 #before: 5.0
  publish_frequency: 5 #before 0.5
  static_map: true
  transform_tolerance: 0.5
  cost_scaling_factor: 6
  inflation_radius: 0.8

